qwikifiers/qwik-ui

.storybook/package.json
packages/core/.storybook/main.ts
packages/core/package.json
packages/core/postcss.config.cjs
packages/core/tailwind.config.cjs

Fix the storybook loading problem after update to nx

Fix the storybook loading problem after update to nx

---

packages/core/src/components/kbd/kbd.stories.tsx
packages/core/src/components/kbd/kbd.tsx
packages/core/src/index.ts
packages/core/src/types/types.ts

Added kbd.ts component

---

.github/PULL_REQUEST_TEMPLATE.md

> Added PR template.
1. To create uniformity to all Pull Requests submitted by contributors.

docs: added pr template

---

CONTRIBUTING.md

As part of `CONTRIBUTING.md` I think it's useful to have basic instructions on how to get a dev workflow running.
I couldn't find any instructions for this so after exploring a bit came up with what seems to me is the intended workflow.
Please let me know if you have an alternative preferred way of working and I can reflect that in the docs.

chore(contributing.md): add instructions for a basic dev workflow

---

packages/daisy/src/components/button/button.tsx
packages/daisy/src/index.ts
packages/headless/src/components/button/button.tsx
packages/headless/src/index.ts
packages/website/src/components/menu/menu.tsx
packages/website/src/routes/daisy/button/index.tsx
packages/website/src/routes/headless/button/index.tsx

feat: add Button component

---

packages/website/src/routes/docs/layout.tsx

fix documents issue

---

packages/daisy/src/components/button-group/button-group.tsx
packages/daisy/src/index.ts
packages/headless/src/components/button-group/button-group.tsx
packages/headless/src/index.ts
packages/website/src/components/menu/menu.tsx
packages/website/src/routes/docs/daisy/button-group/index.tsx
packages/website/src/routes/docs/headless/button-group/button-group.css
packages/website/src/routes/docs/headless/button-group/index.tsx

Added the new ButtonGroup component

feat(component): add ButtonGroup component

---

packages/headless/src/components/drawer/drawer-trigger.tsx
packages/headless/src/components/select/select.tsx

fix: actions/test

---

package-lock.json
packages/material/.eslintrc.json
packages/material/README.md
packages/material/package.json
packages/material/project.json
packages/material/src/components/button/button.tsx
packages/material/src/index.ts
packages/material/tsconfig.json
packages/material/tsconfig.lib.json
packages/material/tsconfig.spec.json
packages/material/vite.config.ts
packages/website/package.json
packages/website/public/materialize.css
packages/website/src/components/material-theme/material-theme.tsx
packages/website/src/components/material-theme/materialize.scss
packages/website/src/components/menu/menu.tsx
packages/website/src/routes/docs/headless/button/index.tsx
packages/website/src/routes/docs/layout.tsx
packages/website/src/routes/docs/material/button/index.scss
packages/website/src/routes/docs/material/button/index.tsx
packages/website/src/routes/index.tsx
tsconfig.base.json

Add material package to test different themes
Closed #78

feat: add material package

---

packages/material/src/components/button/button.tsx
packages/website/src/components/material/material-provider/material-provider.tsx
packages/website/src/components/material/styles/material-icons.css
packages/website/src/routes/docs/material/button/index.tsx

feat: add MaterialButtonProps

---

packages/website/package.json

fix: remove unused dependency

---

packages/daisy/src/components/button/button.tsx
packages/daisy/src/components/button/daisy.config.ts
packages/daisy/src/components/card/card-actions.tsx
packages/daisy/src/components/card/card-body.tsx
packages/daisy/src/components/card/card-image.tsx
packages/daisy/src/components/card/card-title.tsx
packages/daisy/src/components/card/card.tsx
packages/daisy/src/components/card/index.ts
packages/daisy/src/index.ts
packages/headless/src/components/card/card-actions.tsx
packages/headless/src/components/card/card-body.tsx
packages/headless/src/components/card/card-image.tsx
packages/headless/src/components/card/card-title.tsx
packages/headless/src/components/card/card.tsx
packages/headless/src/components/card/index.ts
packages/headless/src/index.ts
packages/website/src/components/menu/menu.tsx
packages/website/src/routes/docs/daisy/button/index.tsx
packages/website/src/routes/docs/daisy/card/index.tsx
packages/website/src/routes/docs/headless/button/index.css
packages/website/src/routes/docs/headless/card/card.css
packages/website/src/routes/docs/headless/card/index.tsx
packages/website/src/routes/docs/index.tsx

The first version of the Card Component. 
```html
<Card>
<CardImage src="https://daisyui.com/images/stock/photo-1606107557195-0e29a4b5b4aa.jpg" alt="shoes" />
<CardBody>
<CardTitle>Card Title</CardTitle>
<p>Lorem ipsum dolor sit amet...</p>         
<CardActions>
<Button>Button 1</Button>
<Button>Button 2</Button>
</CardActions>
</CardBody>
</Card>
```

Feat/card: add the Card component

---

packages/daisy/src/components/button-group/button-group.tsx
packages/daisy/src/components/button/button.tsx
packages/material/src/components/button/button.tsx

- [] Bug
Just renamed the `cls` property in `className`

style: renamed cls in className

---

packages/website/src/routes/docs/index.tsx
packages/website/tailwind.config.cjs

Remove tailwind hack to prevent css purge.

fix: remove tailwind hack to prevent purge

---

CODING_STANDARDS.md
packages/daisy/src/components/button/button.tsx

We want to define standards to align the codebase. This PR is to gather suggestions and contributions from everyone
Closed #91 
Closed #94

define coding standards

---

package-lock.json
packages/daisy/src/components/rating/rating.css
packages/daisy/src/components/rating/rating.tsx
packages/daisy/src/index.ts
packages/headless/src/components/rating/rating.css
packages/headless/src/components/rating/rating.tsx
packages/headless/src/index.ts
packages/website/src/components/menu/menu.tsx
packages/website/src/routes/docs/daisy/rating/index.tsx
packages/website/src/routes/docs/headless/rating/index.css
packages/website/src/routes/docs/headless/rating/index.tsx

Added the first version of the rating component (headless and Daisy)

feat(component): add the rating component

---

packages/headless/src/components/tooltip/tooltip.css
packages/headless/src/components/tooltip/tooltip.tsx

Actual behavior:
https://user-images.githubusercontent.com/300232/219683763-68c0a49b-0f19-4bd4-af33-c809b7d951d4.mov
https://user-images.githubusercontent.com/300232/219683812-3980baca-434b-45de-8d2c-cbce021ee331.mov

[Bug-Fix:Tooltip-Flicker] Debounce showing/hiding the tooltip and css animation fix

---

apps/website/src/components/menu/menu.tsx
apps/website/src/routes/docs/daisy/progress/index.tsx
apps/website/src/routes/docs/headless/progress/index.tsx
packages/daisy/src/components/progress/daisy.config.ts
packages/daisy/src/components/progress/progress.tsx
packages/daisy/src/index.ts
packages/headless/src/components/progress/progress.tsx
packages/headless/src/index.ts

feat(component): add new  Progress Bar component

---

apps/website/src/routes/docs/daisy/accordion/index.tsx
packages/daisy/src/components/progress/progress.tsx
packages/headless/src/components/button/button.cy.tsx

fix: remove warnings

---

packages/headless/src/components/rating/rating.tsx

fix: remove any from Component<any>

---

packages/daisy/src/components/accordion/accordion.tsx

fix(accordion): removed duplicate class in Accordion

---

apps/website/src/routes/docs/daisy/slider/index.tsx
packages/daisy/src/components/slider/daisy.config.ts
packages/daisy/src/components/slider/slider.tsx
packages/daisy/src/index.ts
packages/headless/src/components/slider/slider.tsx
packages/headless/src/components/slider/sliderProgress.tsx
packages/headless/src/components/slider/sliderThumb.tsx

This PR closes #191.
- Expanded the headless slider component to allow customization
- Implemented daisy version

feat: add daisy slider component

---

apps/website/src/components/menu/menu.tsx
apps/website/src/routes/docs/daisy/navigation-bar/index.tsx
apps/website/src/routes/docs/headless/navigation-bar/index.tsx
apps/website/src/routes/docs/headless/navigation-bar/navigation-bar.css
packages/daisy/src/components/navigation-bar/navigation-bar.tsx
packages/daisy/src/index.ts
packages/headless/src/components/navigation-bar/navigation-bar.tsx
packages/headless/src/index.ts

Closed #200
add navigation bar

feat(component): add navigation bar

---

packages/bots/dangerfile.ts

Improve PR linter 
Closed #233 #234

feat: improve PR linter

---

CODING_STANDARDS.md

Add a brief instruction about a11y tests in the coding standards.
Any time components are added / changed.
nc

docs: add a11y instructions in coding standards

---

packages/daisy/type.d.ts
packages/headless/type.d.ts
packages/material/type.d.ts

Clean up the development experience by removing unnecessary warnings.

fix: add css inline definitions

---

apps/website/src/routes/docs/headless/(components)/select/examples.tsx
apps/website/src/routes/docs/headless/(components)/select/index.mdx
apps/website/src/routes/docs/tailwind/(components)/select/index.tsx
packages/kit-headless/src/components/select/select.stories.tsx
packages/kit-headless/src/components/select/select.tsx

Refactors Select to the correct naming convention as requested in #300 
Also fixes #265 which was a regression caused by `useTask$`

refactor(select): change naming convention

---

.gitignore
packages/kit-headless/src/components/accordion/accordion.stories.tsx
packages/kit-headless/src/components/accordion/accordion.tsx

* Update storybook test of Accordion.
* Ensure accessibility and interactivity pass.
nc

feat(accordion) add storybook

---

apps/website/src/routes/docs/tailwind/(getting-started)/introduction/index.tsx

Typo in the docs
https://gyazo.com/c3c036767073471b84fb6769778ff1d3

docs: Typo for Daisy UI

---

packages/kit-headless/src/components/accordion/accordion.tsx
packages/kit-tailwind/src/components/accordion/accordion.tsx

Improve the accordian component.

style(component): Improve the accordian component

---

apps/website/src/routes/docs/tailwind/(components)/accordion/examples.tsx
apps/website/src/routes/docs/tailwind/(components)/accordion/index.mdx
packages/kit-headless/src/components/accordion/accordion.tsx

docs(accordion): add tailwind docs

---

apps/website/src/routes/docs/tailwind/(components)/pagination/index.tsx
packages/kit-headless/src/components/pagination/pagination.stories.tsx
packages/kit-headless/src/components/pagination/pagination.tsx
packages/kit-tailwind/src/components/pagination/pagination.tsx

• improve component type readability
The goal of this PR is to improve the componente readability : 
1) improve types: remove duplicated types, remove redundant types and update type names
2) apply Qwik best practices: extract inline functions

refactor(component): update type names and improve code readability

---

packages/kit-headless/cypress.config.ts
packages/kit-headless/cypress/support/component-index.html
packages/kit-headless/cypress/support/component.ts
packages/kit-headless/src/components/accordion/accordion.spec.tsx

test: added cypress a11y testing

---

package.json
packages/kit-headless/cypress.config.ts
packages/kit-headless/cypress/support/commands.ts
packages/kit-headless/cypress/tsconfig.cy.json
packages/kit-headless/src/components/accordion/accordion.spec.tsx
packages/kit-headless/src/components/tabs/tab.tsx
packages/kit-headless/src/components/tabs/tabs-panel.tsx
packages/kit-headless/src/components/tabs/tabs.spec.tsx
packages/kit-headless/src/components/tabs/tabs.stories.tsx
packages/kit-headless/src/components/tabs/tabs.tsx
packages/kit-headless/tsconfig.editor.json
packages/kit-headless/tsconfig.spec.json
pnpm-lock.yaml

Co-authored-by: Naor Peled <me@naor.dev>
Co-authored-by: Jack Shelton <thejackshelton@users.noreply.github.com># What is it?
Added an example of how to test with Cypress (instead of storybook testing)

test: add tabs cypress tests

---

apps/website/src/routes/docs/headless/(components)/tooltip/index.mdx
packages/kit-headless/src/components/tooltip/tooltip.spec.tsx

Added spec to tooltip and fixed the documentation
#310
I added tests for the tooltip and fixed some content in the documentation.

test(component): added spec to tooltip

---

apps/website/src/components/keyboard-interaction-table/keyboard-interaction-table.tsx
apps/website/src/routes/docs/headless/(components)/tabs/examples.tsx
apps/website/src/routes/docs/headless/(components)/tabs/index.mdx
cypress.config.ts
cypress/fixtures/example.json
cypress/support/commands.ts
cypress/support/e2e.ts
packages/kit-headless/src/components/tabs/tab.tsx
packages/kit-headless/src/components/tabs/tabs-context.type.ts
packages/kit-headless/src/components/tabs/tabs-list.tsx
packages/kit-headless/src/components/tabs/tabs-panel.tsx
packages/kit-headless/src/components/tabs/tabs.spec.tsx
packages/kit-headless/src/components/tabs/tabs.stories.tsx
packages/kit-headless/src/components/tabs/tabs.tsx
packages/kit-headless/src/utils/key-code.type.ts

Getting Tabs to "ready" state

---

packages/kit-headless/src/components/Autocomplete/autocomplete.spec.tsx
packages/kit-headless/src/components/Autocomplete/autocomplete.stories.tsx
packages/kit-headless/src/components/Autocomplete/autocomplete.tsx
packages/kit-headless/src/components/Autocomplete/autocompleteTest.css
packages/kit-headless/src/components/select/select.tsx

Feat: Headless Autocomplete

---

apps/website/src/components/preview-code-example/preview-code-example.tsx

This PR fixes a bug related to insufficient contrast in the `PreviewCodeExample` component's TabPanels in light mode. The issue was caused by the background color not providing enough contrast against the text content, resulting in reduced readability. This accessibility issue can impact users with visual impairments or specific contrast requirements.
The fix addresses this by adjusting the background color to ensure proper contrast, improving the accessibility of the component.
1. When users view the PreviewCodeExample component in light mode, they can now clearly distinguish the TabPanels and read the content without any visibility issues.
1. This fix improves the overall accessibility of the component, ensuring that users with different visual needs can easily interact with the …

fix(preview-code-exmaple): color accessibility

---

apps/website/.eslintrc.json
apps/website/src/routes/docs.css
apps/website/src/routes/docs/headless/(components)/autocomplete/examples.tsx
apps/website/src/routes/docs/headless/(components)/autocomplete/index.mdx
apps/website/src/routes/docs/headless/(components)/select/examples.tsx
packages/kit-headless/src/components/Autocomplete/autocomplete.tsx
packages/kit-headless/src/components/select/select.tsx

Critical UX fixes for autocomplete, docs changes, & TW docs style fix.

---

apps/website/src/_state/component-statuses.ts
apps/website/src/routes/docs/headless/(components)/autocomplete/examples.tsx
apps/website/src/routes/docs/headless/(components)/select/examples.tsx
packages/kit-headless/src/components/Autocomplete/autocomplete.spec.tsx
packages/kit-headless/src/components/Autocomplete/autocomplete.stories.tsx
packages/kit-headless/src/components/Autocomplete/autocomplete.tsx
packages/kit-headless/src/components/tabs/tab.tsx
packages/kit-tailwind/src/components/tabs/tab.tsx

autocomplete tests, attempted fix at website build, disabled support for autocomplete

---

packages/kit-headless/src/components/tabs/tab.tsx
packages/kit-headless/src/index.ts

autocomplete dir rename

---

apps/website/src/components/header/header.tsx
apps/website/src/components/kit-selection-cta/kit-selection-cta.tsx
apps/website/src/components/menu/menu.tsx

Layout+responsive+dark mode: fixed cards layout, responsiveness and dark mode issues, planning to change the whole routing scene
Changing the responsiveness scene along with dark mode Issues etc.
Better UX in general.

fix(website): layout+responsive+dark mode

---

packages/kit-headless/src/components/autocomplete/autocomplete-button.tsx
packages/kit-headless/src/components/autocomplete/autocomplete-context.type.ts
packages/kit-headless/src/components/autocomplete/autocomplete-input.tsx
packages/kit-headless/src/components/autocomplete/autocomplete-listbox.tsx
packages/kit-headless/src/components/autocomplete/autocomplete-root.tsx
packages/kit-headless/src/components/autocomplete/autocomplete.spec.tsx

The following PR fixes the accessibility issues monitored by Axe.

feat(accessibility): axe accessibility recommendation changes

---

apps/website/src/routes/_components/header/header.tsx
apps/website/src/routes/_components/icons/MoonIcon.tsx
apps/website/src/routes/_components/icons/SunIcon.tsx
apps/website/src/routes/index@landing.tsx

docs: fix header

---

packages/kit-headless/src/components/accordion/accordion-context.type.ts
packages/kit-headless/src/components/accordion/accordion-item.tsx
packages/kit-headless/src/components/accordion/accordion-trigger.tsx

refactor(accordion): cleanup unused signals / code

---

apps/website/src/routes/docs/headless/(components)/accordion/index.mdx
packages/kit-headless/src/components/accordion/accordion-trigger.tsx

Accordion improvements

---

apps/website/src/routes/docs/headless/(components)/accordion/examples.tsx
apps/website/src/routes/docs/headless/(components)/accordion/index.mdx
packages/kit-headless/src/components/accordion/accordion-trigger.tsx

docs(accordion): docs improvements, typos, etc

---

apps/website/src/routes/docs/tailwind/(components)/select/index.tsx

fix(select): ts error fix

---

apps/website/src/routes/docs/headless/(components)/accordion/examples.tsx
apps/website/src/routes/docs/headless/(components)/accordion/index.mdx

docs(accordion): dynamic section style changes & removal of alpha banner

---

apps/website/src/routes/index@landing.tsx

refactor(homepage): remove link component on homepage

---

apps/website/src/routes/_components/header/header.tsx
apps/website/src/routes/docs/_components/api-table/api-table.tsx
apps/website/src/routes/docs/_components/status-banner/status-banner.tsx
apps/website/src/routes/docs/headless/(components)/combobox/examples.tsx
apps/website/src/routes/docs/headless/(components)/combobox/index.mdx
packages/kit-headless/src/components/combobox/combobox-icon.tsx
packages/kit-headless/src/components/combobox/combobox-input.tsx
packages/kit-headless/src/components/combobox/combobox.tsx

feat(combobox): search Bar configuration

---

apps/website/src/routes/docs/headless/(components)/combobox/examples.tsx
apps/website/src/routes/docs/headless/(components)/combobox/index.mdx
packages/kit-headless/src/components/combobox/combobox.tsx

fix(combobox): removing extra ref api

---

apps/website/src/global.css
apps/website/src/routes/docs/_components/component-status-badge/component-status-badge.tsx
apps/website/src/routes/docs/_components/navigation-docs/navigation-docs.tsx
apps/website/src/routes/layout.tsx
packages/kit-headless/src/components/combobox/combobox.spec.tsx
packages/kit-headless/src/components/combobox/utils.ts

fix(combobox): fix race condition issue with disabled options

---

apps/website/src/global.css
apps/website/src/routes/_components/footer/footer.tsx
apps/website/src/routes/_components/header/header.tsx
apps/website/src/routes/docs.css
apps/website/src/routes/docs/_components/anatomy-table/anatomy-table.tsx
apps/website/src/routes/docs/_components/api-table/api-table.tsx
apps/website/src/routes/docs/_components/component-status-badge/component-status-badge.tsx
apps/website/src/routes/docs/_components/keyboard-interaction-table/keyboard-interaction-table.tsx
apps/website/src/routes/docs/_components/navigation-docs/navigation-docs.tsx
apps/website/src/routes/docs/_components/preview-code-example/preview-code-example.tsx
apps/website/src/routes/docs/fluffy/(components)/button/index.tsx
apps/website/src/routes/docs/headless/(components)/combobox/index.mdx
apps/website/src/routes/index@landing.tsx
apps/website/tailwind.config.cjs
package.json
packages/kit-headless/src/components/combobox/combobox-input.tsx
packages/kit-headless/src/components/combobox/combobox.spec.tsx
packages/kit-headless/src/components/combobox/utils.ts
pnpm-lock.yaml

fix(cypress): tests fixes, docs improvements

---

packages/kit-fluffy/package.json
packages/kit-headless/package.json
packages/kit-material/package.json
packages/kit-tailwind/package.json

fix(types): types no longer under qwik-ui/

---

package.json
pnpm-lock.yaml

fix(docs): upgrading dependencies of wrangler & nx-cloudflare

---

apps/website/src/routes/docs/_components/highlight/get-or-create-highlighter.ts
apps/website/src/routes/docs/_components/highlight/highlight.tsx
package.json
pnpm-lock.yaml

fix(docs): replacing shiki with shikiji

---

apps/website/src/_state/app-state.type.ts

fix(docs): fix missing import

---

apps/website/src/_state/app-state.type.ts
apps/website/src/routes/docs/_components/highlight/get-or-create-highlighter.ts
apps/website/src/routes/docs/_components/highlight/highlight.tsx
package.json
pnpm-lock.yaml

fix(docs): back to shiki instead of shikiji

---

apps/website/README.md
apps/website/adapters/cloudflare-pages/vite.config.ts
apps/website/package.json
apps/website/project.json
apps/website/src/entry.cloudflare-pages.tsx
apps/website/src/routes/docs/_components/highlight/highlight.tsx
apps/website/src/routes/docs/headless/(components)/badge/index.tsx
apps/website/src/routes/docs/headless/(components)/toggle/index.mdx
package.json
pnpm-lock.yaml

revert to pr 458

---

packages/kit-fluffy/vite.config.ts
packages/kit-headless/vite.config.ts
packages/kit-material/vite.config.ts
packages/kit-tailwind/vite.config.ts
packages/primitives/vite.config.ts

Fixes are grammatical and involve only comments in `vite.config.ts` files.

fix(typos): minor typo correction in comments

---

packages/kit-headless/src/components/combobox/combobox-option.tsx

fix: combobox test

---

CONTRIBUTING.md

Old snippets do not currently work. This commit replaces them for ones that do.
Current testing code snippets do not work. This commit fixes that. 
- 1. Working code snippets

docs: fixed snippets for testing repo

---

apps/website/src/root.tsx
apps/website/src/routes/docs/_components/highlight/highlight.tsx

workaround
I have read the CLA Document and I hereby sign the CLA

refactor: hacky workaround

---

apps/website/src/root.tsx
apps/website/src/routes/docs/_components/highlight/highlight.tsx

refactor: fix async workaround

---

apps/website/src/routes/docs/headless/(components)/toggle/index.mdx

fix(toggle): toggle page removing unimported component

---

apps/website/src/routes/docs/_components/highlight/highlight.tsx

fix(code flicker): removes code flicker on page load

---

CONTRIBUTING.md

1. Adds new commands that could be useful to the reader
2. Improves commands that  are already present
3. Adds links to used libraries

chore: improve CONTRIBUTING.md

---

.all-contributorsrc

fix: change all-contributorsrc

---

.github/workflows/release.yml
.github/workflows/test.yml

fix #508
Run tests against node 18, 20 and 21
Cover Node LTS and latest versions

ci(test and release): run tests against node 18, 20 and 21

---

package.json
pnpm-lock.yaml

temporarily remove nx patch and use latest qwik build and vite version

docs: fix blank screen

---

packages/kit-headless/src/components/select/select-listbox.tsx
packages/kit-headless/src/components/select/select.spec.tsx

A suprisingly quick code change gets rid of  the visibleTask
your screenshots here -->

refactor(select-listbox): removed useVisibleTask

---

apps/website/src/components/code-snippet/code-snippet.tsx
apps/website/src/components/mdx-components/index.tsx
apps/website/src/components/showcase/showcase.tsx

docs(eslint no-any): add eslint-ignore comments for unavoidable any(s)

---

.eslintrc.json
apps/website/src/routes/docs/fluffy/(getting-started)/introduction/index.mdx
apps/website/src/routes/docs/headless/install/index.mdx
apps/website/src/routes/docs/headless/introduction/index.mdx
apps/website/src/routes/docs/headless/modal/index.mdx

fix(docs site build does not hang): docs site build does not hang

---

package.json
packages/kit-headless/cypress.config.ts
packages/kit-headless/cypress/support/component.ts
pnpm-lock.yaml

fix(docs): remove visual regression cypress plugin with sharp

---

apps/website/src/components/note/note.tsx

Didn't add a "fun fact" as I'm not sure it's really needed. Hard to find the right icon for it as well. "Info" is probably good enough.

docs(note): remove success and use css vars where possible

---

package.json
packages/kit-headless/package.json
packages/kit-headless/src/components/modal/modal-behavior.ts
packages/kit-headless/src/components/modal/modal.tsx
pnpm-lock.yaml

fix(modal): modal on iOS maintains proper scroll position & proper escape scroll unlock when tabbing

---

apps/website/src/components/mdx-components/index.tsx
apps/website/src/routes/docs/headless/combobox/examples/custom-filter.tsx
apps/website/src/routes/docs/headless/combobox/examples/custom-keys.tsx
apps/website/src/routes/docs/headless/combobox/examples/default-label.tsx
apps/website/src/routes/docs/headless/combobox/examples/disable-blur.tsx
apps/website/src/routes/docs/headless/combobox/examples/disabled.tsx
apps/website/src/routes/docs/headless/combobox/examples/hero.tsx
apps/website/src/routes/docs/headless/combobox/examples/hide.tsx
apps/website/src/routes/docs/headless/combobox/examples/highlighted-index.tsx
apps/website/src/routes/docs/headless/combobox/examples/object.tsx
apps/website/src/routes/docs/headless/combobox/examples/placement.tsx
apps/website/src/routes/docs/headless/combobox/examples/search-bar.tsx
apps/website/src/routes/docs/headless/combobox/examples/shift.tsx
apps/website/src/routes/docs/headless/combobox/examples/signal-binds.tsx
apps/website/src/routes/docs/headless/combobox/examples/sort-filter.tsx
apps/website/src/routes/docs/headless/combobox/examples/string.tsx
apps/website/src/routes/docs/headless/popover/examples/auto-placement.tsx
apps/website/src/routes/docs/headless/popover/examples/flip.tsx
apps/website/src/routes/docs/headless/popover/examples/floating-intro.tsx
apps/website/src/routes/docs/headless/popover/examples/gutter.tsx
apps/website/src/routes/docs/headless/popover/examples/listbox-animation.tsx
apps/website/src/routes/docs/headless/popover/examples/placement.tsx
apps/website/src/routes/docs/headless/popover/index.mdx
packages/kit-headless/src/components/popover/popover-impl.tsx
packages/kit-headless/src/components/popover/utils.ts

docs(improves code mdx and combobox examples)

---

package.json
packages/kit-headless/package.json
pnpm-lock.yaml

fix(docs): attempt to fix deploy

---

apps/website/src/routes/docs/headless/combobox/examples/hero.css
apps/website/src/routes/docs/headless/combobox/examples/hero.tsx
apps/website/src/routes/docs/headless/popover/examples/listbox-animation.tsx
packages/kit-headless/src/components/popover/floating.tsx
packages/kit-headless/src/components/popover/utils.ts

fix(popover combobox): fixes floating ui flicker, animations

---

package.json
pnpm-lock.yaml

fix(docs): move sharp to dep

---

.github/actions/release-minor/action.yml
.github/workflows/release-minor.yml
packages/kit-headless/project.json
packages/utils/project.json

ci: added release minor

---

.github/workflows/release-minor.yml

ci(minor release): rename duplicate release name to release minor

---

packages/kit-headless/src/components/combobox/combobox-portal.tsx

docs(combobox): deprecation warning on ComboboxPortal

---

packages/kit-headless/package.json
pnpm-lock.yaml

chore(headless): update peerDependencies

---

packages/kit-headless/src/components/tabs/tab.tsx

refactor(tabs): removed last visible task with sync$

---

apps/website/src/components/mdx-components/index.tsx

fix(mdx-components): fix pre scrollbar

---

.changeset/honest-timers-dream.md
apps/website/src/routes/docs/headless/combobox/examples/hero.tsx
apps/website/src/routes/docs/headless/combobox/examples/highlighted-index.tsx
apps/website/src/routes/docs/headless/combobox/examples/placement.tsx
apps/website/src/routes/docs/headless/combobox/examples/search-bar.tsx
apps/website/src/routes/docs/headless/combobox/examples/shift.tsx
apps/website/src/routes/docs/headless/combobox/examples/signal-binds.tsx
apps/website/src/routes/docs/headless/combobox/index.mdx
packages/kit-headless/src/components/combobox/combobox-context.type.ts
packages/kit-headless/src/components/combobox/combobox-input.tsx
packages/kit-headless/src/components/combobox/combobox-option.tsx
packages/kit-headless/src/components/combobox/combobox.spec.tsx
packages/kit-headless/src/components/combobox/combobox.tsx
packages/kit-headless/src/index.ts

New bind:selectedIndex syntax, bug fixes

---

.vscode/extensions.json
apps/website/.eslintrc.json
apps/website/e2e/example.spec.ts
apps/website/playwright.config.ts
apps/website/project.json
package.json
pnpm-lock.yaml

So that we can currently do tests, whilst waiting on the playwright component test integration.

Adding in playwright e2e tests (nx v17)

---

apps/website/src/root.tsx

docs: enable styled feature flag

---

.github/actions/test/action.yml
apps/website/project.json
packages/cli/project.json
packages/kit-headless/project.json
packages/kit-styled/components-registry.json
packages/kit-styled/package.json
packages/kit-styled/project.json

validation of correctness
We need to remember to bring back tagging of last release and "affected"

turned on tests on ci for all packages

---

apps/website/src/components/header/header.tsx
apps/website/src/components/icons/logo.tsx

chore: remove useless code

---

apps/website/src/routes/docs/headless/select/examples/add-users.tsx
apps/website/src/routes/docs/headless/select/examples/change-value.tsx
apps/website/src/routes/docs/headless/select/examples/controlled.tsx
apps/website/src/routes/docs/headless/select/examples/disabled.tsx
apps/website/src/routes/docs/headless/select/examples/group.tsx
apps/website/src/routes/docs/headless/select/examples/loop.tsx
apps/website/src/routes/docs/headless/select/examples/open-change.tsx
apps/website/src/routes/docs/headless/select/examples/scrollable.tsx
apps/website/src/routes/docs/headless/select/examples/typeahead.tsx
apps/website/src/routes/docs/headless/select/index.mdx
apps/website/src/routes/docs/headless/select/select.driver.ts
apps/website/src/routes/docs/headless/select/select.spec.ts
packages/kit-headless/src/components/select/index.ts
packages/kit-headless/src/components/select/notes.md
packages/kit-headless/src/components/select/select-context.ts
packages/kit-headless/src/components/select/select-group.tsx
packages/kit-headless/src/components/select/select-inline.tsx
packages/kit-headless/src/components/select/select-label.tsx
packages/kit-headless/src/components/select/select-option.tsx
packages/kit-headless/src/components/select/select-trigger.tsx
packages/kit-headless/src/components/select/select-value.tsx
packages/kit-headless/src/components/select/select.tsx
packages/kit-headless/src/components/select/use-select.tsx
packages/kit-headless/src/components/select/utils.ts

Select Features, Tests

---

apps/website/src/routes/docs/headless/contributing/index.mdx
apps/website/src/routes/docs/headless/select/examples/add-users.tsx
apps/website/src/routes/docs/headless/select/examples/change-value.tsx
apps/website/src/routes/docs/headless/select/examples/controlled-value.tsx
apps/website/src/routes/docs/headless/select/examples/controlled.tsx
apps/website/src/routes/docs/headless/select/examples/disabled.tsx
apps/website/src/routes/docs/headless/select/examples/group.tsx
apps/website/src/routes/docs/headless/select/examples/hero.tsx
apps/website/src/routes/docs/headless/select/examples/loop.tsx
apps/website/src/routes/docs/headless/select/examples/open-change.tsx
apps/website/src/routes/docs/headless/select/examples/option-value.tsx
apps/website/src/routes/docs/headless/select/examples/scrollable.tsx
apps/website/src/routes/docs/headless/select/examples/select.css
apps/website/src/routes/docs/headless/select/examples/typeahead.tsx
apps/website/src/routes/docs/headless/select/examples/uncontrolled.tsx
apps/website/src/routes/docs/headless/select/examples/wrong-value.tsx
apps/website/src/routes/docs/headless/select/index.mdx
apps/website/src/routes/docs/headless/select/select.spec.ts
apps/website/src/routes/docs/headless/select/snippets/building-blocks.tsx
packages/kit-headless/src/components/popover/floating.tsx
packages/kit-headless/src/components/select/notes.md
packages/kit-headless/src/components/select/select-inline.tsx
packages/kit-headless/src/components/select/select-option.tsx
packages/kit-headless/src/components/select/select-trigger.tsx
packages/kit-headless/src/components/select/select-value.tsx
packages/kit-headless/src/components/select/select.tsx
packages/kit-headless/src/components/select/use-select.tsx

Select: Top layer behavior

---

apps/website/adapters/cloudflare-pages/vite.config.ts
apps/website/src/components/highlight/highlight.tsx
package.json
pnpm-lock.yaml

docs(shiki): use cloudflareAdapter SSG mode for every page

---

.changeset/great-pigs-divide.md
packages/kit-headless/package.json
packages/kit-headless/src/components/collapsible/notes.md

Fix: package types

---

.changeset/short-dogs-press.md
apps/website/adapters/cloudflare-pages/vite.config.ts
apps/website/src/_state/component-statuses.ts
apps/website/src/routes/docs/headless/carousel/examples/carousel.css
apps/website/src/routes/docs/headless/carousel/examples/hero.tsx
apps/website/src/routes/docs/headless/carousel/index.mdx
apps/website/src/routes/docs/headless/menu.md
package.json
packages/kit-headless/src/components/carousel/carousel-container.tsx
packages/kit-headless/src/components/carousel/carousel-context-id.ts
packages/kit-headless/src/components/carousel/carousel-context.type.ts
packages/kit-headless/src/components/carousel/carousel-viewport.tsx
packages/kit-headless/src/components/carousel/carousel.tsx
packages/kit-headless/src/components/carousel/index.ts
packages/kit-headless/src/components/carousel/next-button.tsx
packages/kit-headless/src/components/carousel/pagination.tsx
packages/kit-headless/src/components/carousel/prev-button.tsx
packages/kit-headless/src/components/carousel/slide.tsx
packages/kit-headless/src/components/carousel/types.ts
packages/kit-headless/src/components/carousel/utils.ts
packages/kit-headless/src/index.ts
pnpm-lock.yaml

Add carousel component as draft

---

apps/website/adapters/cloudflare-pages/vite.config.ts

This reverts commit 9af7143be27711dd4c4be78785f99200a80f06e1.

Revert "fix(cloudflare vite.config): re-add add @ts-expect-error"

---

apps/website/src/components/highlight/highlight.tsx

fix(website): only bundle what we use for shiki

---

.changeset/green-months-camp.md
packages/kit-headless/src/components/select/hidden-select.tsx
packages/kit-headless/src/components/select/index.ts
packages/kit-headless/src/components/select/select-inline.tsx
packages/kit-headless/src/components/select/select.tsx

feat(select): hidden select is synchronized with headless select

---

apps/website/src/components/highlight/highlight.tsx
apps/website/src/routes/docs/headless/accordion/examples/custom-heading.tsx
apps/website/src/routes/docs/headless/accordion/examples/default-value.tsx
apps/website/src/routes/docs/headless/accordion/examples/disabled.tsx
apps/website/src/routes/docs/headless/accordion/examples/dynamic.tsx
apps/website/src/routes/docs/headless/accordion/examples/focused-index.tsx
apps/website/src/routes/docs/headless/accordion/examples/hero.tsx
apps/website/src/routes/docs/headless/accordion/examples/multi.tsx
apps/website/src/routes/docs/headless/accordion/examples/non-collapsible.tsx
apps/website/src/routes/docs/headless/accordion/examples/selected-index.tsx
apps/website/src/routes/docs/headless/collapsible/examples/bind-open.tsx
apps/website/src/routes/docs/headless/collapsible/index.mdx
apps/website/src/routes/docs/headless/select/index.mdx
apps/website/src/routes/docs/headless/tabs/examples/disabled.tsx
apps/website/src/routes/docs/headless/tabs/index.css

fix: docs examples

---

.changeset/eleven-bulldogs-hug.md
apps/website/src/routes/docs/headless/collapsible/examples/open-change.tsx
apps/website/src/routes/docs/headless/collapsible/examples/programmatic.tsx
apps/website/src/routes/docs/headless/modal/index.mdx
apps/website/src/routes/docs/headless/modal/snippets/stripped-styles.css
packages/kit-headless/src/components/collapsible/collapsible.test.ts

tests: larger collapsible test suite

---

apps/website/src/components/mdx-components/index.tsx
apps/website/src/routes/docs/styled/(getting-started)/install/index.mdx

To show how to generate style components in one's project

added more cli instructions and color to links

---

CONTRIBUTING.md

docs: fix typos in the contribution guidelines

---

.changeset/lucky-carrots-pay.md
apps/website/src/routes/docs/headless/collapsible/examples/csr.tsx
apps/website/src/routes/docs/headless/collapsible/index.mdx
packages/kit-headless/src/components/collapsible/collapsible-content.tsx
packages/kit-headless/src/components/collapsible/collapsible.test.ts

fix: collapsible renders correctly on CSR

---

.changeset/ninety-shoes-buy.md

add headless label changeset

---

.github/workflows/cla.yml

chore(cla.yml): set lock-pullrequest-aftermerge to false

---

apps/component-tests/src/routes/[kit]/[component]/[example]/index.tsx
apps/website/src/routes/docs/headless/popover/examples/hero.tsx
packages/kit-headless/src/components/popover/popover.driver.ts
packages/kit-headless/src/components/popover/popover.test.ts

[WIP] Popover E2E tests 🚧

---

apps/website/src/routes/docs/headless/popover/examples/programmatic.tsx
packages/kit-headless/src/components/popover/popover-impl.tsx
packages/kit-headless/src/components/popover/popover-trigger.tsx
packages/kit-headless/src/components/popover/popover.test.ts

fix: popover flakiness

---

.changeset/blue-spiders-flash.md
apps/website/src/routes/docs/headless/popover/examples/basic.tsx
apps/website/src/routes/docs/headless/popover/examples/hero.tsx
apps/website/src/routes/docs/headless/popover/index.mdx
packages/kit-headless/src/components/popover/popover.driver.ts
packages/kit-headless/src/components/popover/popover.test.ts

refactor: improved popover middle tests

---

.changeset/six-cheetahs-bow.md
.changeset/thirty-carrots-sip.md
apps/website/src/routes/docs/headless/popover/examples/basic.tsx
apps/website/src/routes/docs/headless/popover/examples/hero.tsx
apps/website/src/routes/docs/headless/popover/examples/hide.tsx
apps/website/src/routes/docs/headless/popover/examples/show.tsx
apps/website/src/routes/docs/headless/popover/examples/toggle.tsx
packages/kit-headless/src/components/popover/popover-trigger.tsx
packages/kit-headless/src/components/popover/popover.test.ts

Improve popover test suite

---

apps/website/src/routes/docs/headless/select/examples/bind-open.tsx
apps/website/src/routes/docs/headless/select/examples/controlled-value.tsx
apps/website/src/routes/docs/headless/select/examples/form.tsx
apps/website/src/routes/docs/headless/select/examples/group.tsx
apps/website/src/routes/docs/headless/select/examples/hero.tsx
apps/website/src/routes/docs/headless/select/examples/multiple.tsx
apps/website/src/routes/docs/headless/select/examples/scrollable.tsx
apps/website/src/routes/docs/headless/select/index.mdx
apps/website/src/routes/docs/headless/select/snippets/building-blocks.tsx
apps/website/src/routes/docs/headless/select/snippets/select.css
packages/kit-headless/src/components/select/hidden-select.tsx
packages/kit-headless/src/components/select/index.ts
packages/kit-headless/src/components/select/select-context.ts
packages/kit-headless/src/components/select/select-group-label.tsx
packages/kit-headless/src/components/select/select-group.tsx
packages/kit-headless/src/components/select/select-inline.tsx
packages/kit-headless/src/components/select/select-label.tsx
packages/kit-headless/src/components/select/select-option.tsx
packages/kit-headless/src/components/select/select-trigger.tsx
packages/kit-headless/src/components/select/select-value.tsx
packages/kit-headless/src/components/select/select.driver.ts
packages/kit-headless/src/components/select/select.test.ts
packages/kit-headless/src/components/select/select.tsx
packages/kit-headless/src/components/select/use-select.tsx

Initial multi-select capabilities

---

apps/website/src/routes/docs/styled/(getting-started)/introduction/index.mdx

docs(styled introduction): update quote link

---

apps/website/src/components/mdx-components/index.tsx
apps/website/src/routes/docs/headless/accordion/examples/custom-heading.tsx
apps/website/src/routes/docs/headless/accordion/examples/default-value.tsx
apps/website/src/routes/docs/headless/accordion/examples/disabled.tsx
apps/website/src/routes/docs/headless/accordion/examples/dynamic.tsx
apps/website/src/routes/docs/headless/accordion/examples/focused-index.tsx
apps/website/src/routes/docs/headless/accordion/examples/hero.tsx
apps/website/src/routes/docs/headless/accordion/examples/multi.tsx
apps/website/src/routes/docs/headless/accordion/examples/non-collapsible.tsx
apps/website/src/routes/docs/headless/accordion/examples/selected-index.tsx
apps/website/src/routes/docs/headless/accordion/index.mdx
apps/website/src/routes/docs/headless/accordion/snippets/building-blocks.tsx
apps/website/src/routes/docs/headless/install/examples/accordion-qwik-city.tsx
apps/website/src/routes/docs/headless/install/examples/accordion.tsx
apps/website/src/routes/docs/headless/install/examples/astro-accordion.tsx
apps/website/src/routes/docs/headless/install/snippets/building-blocks.tsx
apps/website/src/routes/docs/headless/introduction/index.mdx
apps/website/src/routes/docs/styled/accordion/examples/hero.tsx
apps/website/src/routes/docs/styled/accordion/index.mdx
packages/kit-headless/src/components/accordion/accordion.spec.tsx
packages/kit-headless/src/components/accordion/index.ts
packages/kit-headless/src/index.ts
packages/kit-styled/src/components/accordion/accordion.tsx

search & replace + docs fix

---

.github/workflows/test.yml

fix(pkg.pr.new): try using dist folder

---

packages/kit-styled/src/components/checkbox/checkbox.tsx
packages/kit-styled/src/components/input/input.tsx
packages/kit-styled/src/components/textarea/textarea.tsx

refactor(styled input/checkbox/textarea): improve handling of name/id props

---

.github/workflows/test.yml

fix(pkg.pr.new):separate the job into a new "continuous-release" workflow

---

apps/website/src/routes/docs/headless/popover/index.mdx
apps/website/src/routes/docs/headless/popover/snippets/popover.css
packages/kit-headless/src/components/popover/popover-panel-impl.tsx
packages/kit-headless/src/components/popover/utils.ts

popover data attribute refactor

---

apps/website/src/routes/docs/styled/checkbox/examples/data-binding.tsx
apps/website/src/routes/docs/styled/checkbox/index.mdx
apps/website/src/routes/docs/styled/input/examples/data-binding.tsx
apps/website/src/routes/docs/styled/input/examples/hero.tsx
apps/website/src/routes/docs/styled/input/index.mdx
apps/website/src/routes/docs/styled/textarea/examples/data-binding.tsx
apps/website/src/routes/docs/styled/textarea/index.mdx
packages/kit-styled/src/components/checkbox/checkbox.tsx
packages/kit-styled/src/components/input/input.tsx
packages/kit-styled/src/components/textarea/textarea.tsx

Fix input/textarea/checkbox two way data binding

---

packages/kit-styled/src/components/input/input.tsx

chore(styled input): remove ref

---

apps/website/src/routes/docs/styled/checkbox/examples/data-binding.tsx

chore(styled checkbox): @ts-expect-error data-binding example

---

.changeset/two-glasses-fix.md
apps/website/src/routes/docs/headless/accordion/examples/animation.tsx
apps/website/src/routes/docs/headless/accordion/index.mdx
apps/website/src/routes/docs/headless/collapsible/examples/animation.tsx
apps/website/src/routes/docs/headless/collapsible/index.mdx
packages/kit-headless/src/components/accordion/accordion-item.tsx
packages/kit-headless/src/components/collapsible/collapsible-content.tsx
packages/kit-headless/src/components/collapsible/collapsible-context.type.ts
packages/kit-headless/src/components/collapsible/collapsible.tsx

Accordion animation

---

packages/kit-headless/src/components/collapsible/collapsible.tsx
packages/kit-headless/src/components/collapsible/use-collapsible.tsx

fix: consume getHiddenHeight inside of component$

---

packages/kit-headless/src/components/collapsible/collapsible-content.tsx
packages/kit-headless/src/components/collapsible/collapsible-context-id.ts
packages/kit-headless/src/components/collapsible/collapsible-context.ts
packages/kit-headless/src/components/collapsible/collapsible-trigger.tsx
packages/kit-headless/src/components/collapsible/collapsible.tsx
packages/kit-headless/src/components/collapsible/index.ts

fix: remove context exports and refactor context file: collapsible

---

packages/kit-headless/src/components/popover/popover-panel-impl.tsx
packages/kit-headless/src/components/popover/utils.ts
packages/kit-styled/src/components/popover/popover.tsx

refactor(styled popover): to use data-open data-closing

---

apps/website/src/routes/docs/styled/accordion/index.mdx
apps/website/src/routes/docs/styled/button/index.mdx
apps/website/src/routes/docs/styled/checkbox/index.mdx
apps/website/src/routes/docs/styled/input/index.mdx
apps/website/src/routes/docs/styled/popover/index.mdx
apps/website/src/routes/docs/styled/textarea/index.mdx
packages/kit-styled/src/components/accordion/accordion.tsx
packages/kit-styled/src/components/checkbox/checkbox.tsx

Docs-small-fixes

---

apps/website/src/routes/docs/styled/(getting-started)/install/index.mdx
packages/kit-styled/src/components/checkbox/checkbox.tsx

docs(styled install): add barrel file bonus step

---

.changeset/orange-points-reflect.md
.changeset/slimy-snakes-poke.md

chore(changeset): add tailwind.config and Accordion changes

---

.changeset/fast-actors-report.md

add correct img path

---

.changeset/fast-actors-report.md

change to external link

---

.changeset/fast-actors-report.md

image address

---

packages/kit-headless/src/components/select/select-inline.tsx

fix: I have read the CLA Document and I hereby sign the CLA

---

.changeset/calm-lizards-tie.md
packages/kit-headless/package.json
packages/kit-headless/vite.config.ts
pnpm-lock.yaml

Co-authored-by: Jack Shelton <thejackshelton@users.noreply.github.com>

fix(preserveModules): add external deps

---

packages/kit-headless/package.json
packages/kit-headless/vite.config.ts
pnpm-lock.yaml

chore(kit-headless/package.json): move peer deps to deps

---

apps/website/src/components/toc/toc.tsx

fix(toc): add rootMargin

---

.changeset/late-ravens-smoke.md
apps/website/src/routes/docs/headless/select/examples/validation.tsx
packages/kit-headless/src/components/select/hidden-select-option.tsx
packages/kit-headless/src/components/select/hidden-select.tsx
packages/kit-headless/src/components/select/select.test.ts

Fix validation

---

packages/kit-styled/src/components/input/input.tsx

Added input name props in styled Input component

fix: added name props

---

.changeset/gorgeous-falcons-care.md
apps/website/src/routes/docs/headless/select/examples/description.tsx
apps/website/src/routes/docs/headless/select/examples/validation.tsx
apps/website/src/routes/docs/headless/select/index.mdx
apps/website/src/routes/docs/headless/select/snippets/select.css
packages/kit-headless/src/components/accordion/accordion-root.tsx
packages/kit-headless/src/components/select/hidden-select.tsx
packages/kit-headless/src/components/select/index.ts
packages/kit-headless/src/components/select/select-context.ts
packages/kit-headless/src/components/select/select-display-value.tsx
packages/kit-headless/src/components/select/select-error-message.tsx
packages/kit-headless/src/components/select/select-inline.tsx
packages/kit-headless/src/components/select/select-listbox.tsx
packages/kit-headless/src/components/select/select-popover.tsx
packages/kit-headless/src/components/select/select-root.tsx
packages/kit-headless/src/components/select/select-trigger.tsx
packages/kit-styled/src/components/select/select.tsx

export select description

---

.changeset/pink-pans-melt.md
apps/website/src/routes/docs/headless/popover/examples/programmatic.tsx
apps/website/src/routes/docs/headless/popover/examples/test-hide.tsx
apps/website/src/routes/docs/headless/popover/examples/test-popover-overlap.tsx
apps/website/src/routes/docs/headless/popover/examples/test-show.tsx
packages/kit-headless/src/components/popover/popover.test.ts

We need to fortify our popover tests. Fixes [#830](https://github.com/qwikifiers/qwik-ui/issues/830)

chore(popover): add final tests for the popover

---

apps/website/src/routes/docs/styled/checkbox/examples/data-binding.tsx

chore: remove ts-expect-error

---

apps/website/src/routes/docs/styled/alert/index.mdx
apps/website/src/routes/docs/styled/skeleton/index.mdx

fix classNames

---

apps/website/src/routes/docs/headless/separator/index.mdx

docs(separator.mdx): fix headings levels

---

.gitignore

chore: add .nx/workspace-data to .gitignore

---

apps/website/adapters/cloudflare-pages/vite.config.ts

feat: update vite.config.ts

---

apps/website/src/_state/component-statuses.ts
apps/website/src/routes/docs/headless/checkbox/examples/test-list.tsx
apps/website/src/routes/docs/headless/checkbox/index.mdx
apps/website/src/routes/docs/headless/checkbox/snippets/building-blocks.tsx

fix: build and checkbox docs

---

apps/website/src/components/toc/toc.tsx

fix(toc): handles upwards discontinuity

---

apps/website/src/components/icons/MenuIcon.tsx

fix(MenuIcon.tsx): remove double stroke

---

packages/kit-headless/src/components/accordion/accordion-content.tsx

This reverts commit fed7c2f43bfd89f9eca19cc449bb496a6f615466.

Revert "my cvommit"

---

apps/website/src/components/toc/toc.tsx

The more I tried to fix the template logic  the more confident I have become that the shadcn nested ternaries JSX logic is harder to read and way more error prone. 
This is a workaround. I don't want to fix this bug unless we change the template to multiple ifs statements with returns.

Toc readability

---

.changeset/stale-mails-do.md
apps/website/src/routes/docs/headless/combobox/index.mdx
apps/website/src/routes/docs/headless/select/examples/hero.tsx

mark refs as experimental

---

apps/website/src/routes/docs/styled/(getting-started)/install/index.mdx

docs: tailwind classes intelliSense autocompletion in vscode for styled util functions

---

apps/website/src/components/toc/toc.tsx

fix(toc): preview not happy

---

.github/actions/setup/action.yml
migrations.json
package.json
pnpm-lock.yaml

chore(package.json): bump nx and pnpm

---

apps/website/src/components/code-snippet/code-snippet.tsx
apps/website/src/components/showcase/component-imports.ts

chore(import.meta.glob): change `as: 'raw'` to `query: '?raw'`

---

apps/website/src/components/code-snippet/code-snippet.tsx
apps/website/src/components/showcase/component-imports.ts

fix(shiki): add import 'default' since it is needed with new query: '?raw'

---

package.json
packages/kit-headless/package.json
packages/kit-styled/package.json
pnpm-lock.yaml

Because we upgraded to 1.7, we also get the dev mode issues of 1.7 😅 . Upgrading to 1.7.1 with wout's fixes.

upgrade to 1.7.1

---

packages/kit-styled/src/components/checkbox/checkbox.tsx

fix checkbox name prop

---

packages/cli/bin/index.ts

fix cli typo

---

.github/actions/setup/action.yml
apps/website/src/components/highlight/highlight.tsx
package.json
pnpm-lock.yaml

chore: bump pnpm

---

apps/website/src/root.tsx

change to new sw impl

---

.github/actions/setup/action.yml
package.json

chore(pnpm): bump to 9.7.0

---

apps/website/src/root.tsx

Revert-new-sw

---

packages/themes/src/lib/provider.tsx

fix: comment out bundle issue when changing user pref

---

.changeset/old-spiders-burn.md

add utils changeset

---

packages/themes/src/lib/provider.tsx

chore(/themes): turn visible task to strategy:document-idle

---

apps/website/src/components/copy-css-config/copy-css-config.tsx
packages/themes/src/lib/provider.tsx
packages/themes/src/lib/types.ts

fix(website): remove js execution on load by assigning themes sig on click

---

apps/website/src/routes/docs/styled/(getting-started)/install/index.mdx

fix(docs): typo

---

apps/website/auto-api.ts
apps/website/src/components/api-table/auto-api.tsx
apps/website/src/routes/docs/headless/carousel/auto-api/api.ts
apps/website/src/routes/docs/headless/carousel/index.mdx
apps/website/src/routes/docs/headless/select/index.mdx
packages/kit-headless/src/components/carousel/inline.tsx
packages/kit-headless/src/components/carousel/root.tsx
packages/kit-headless/src/components/toggle-group/index.tsx
packages/kit-headless/src/index.ts

fixes type errors, improves bundling of toggle group, improves auto API handling of objects and unions.

Site improvements

---

.changeset/moody-cycles-cheat.md
apps/component-tests/src/global.css
apps/component-tests/src/root.tsx

fix:global css isnt the same in  component-test and website

---

apps/website/public/robots.txt

chore(robot.txt): add aloglia crawler

---

.changeset/two-jeans-share.md

chore: remove wrong minor release changeset, it was just a docs change

---

.changeset/two-jeans-share.md

Remove-wrong-minor-changeset

---

.changeset/cuddly-cups-float.md
packages/kit-headless/package.json
packages/kit-styled/package.json
packages/themes/package.json
pnpm-lock.yaml

chore: set peer Dependencies to 1.3.1

---

apps/website/src/routes/docs/styled/(getting-started)/install/index.mdx
packages/kit-styled/components-registry.json

Add-missing-cli-registry-components

---

apps/website/src/routes/docs/headless/combobox/auto-api/api.ts
apps/website/src/routes/docs/headless/dropdown/auto-api/api.ts
packages/kit-headless/src/components/combobox/combobox-input.tsx
packages/kit-headless/src/components/combobox/use-combobox.tsx
packages/kit-headless/src/components/dropdown/dropdown-root.tsx
packages/kit-headless/src/components/dropdown/use-dropdown.tsx

Dropdown and Combobox no longer use QRL's in computed signals so that they work in v2.

fix: qrl's inside computed

---

.changeset/real-chairs-tickle.md
apps/website/src/routes/docs/headless/collapsible/auto-api/api.ts
packages/kit-headless/src/components/collapsible/collapsible-trigger.tsx

This is really important for ADA

fix: collapsible trigger has correct id

---

.changeset/light-penguins-design.md

To release the changes to npm 
Follow up of #993

added missing changeset for added styled components

---

.changeset/shy-bottles-agree.md
.changeset/tender-pens-run.md
packages/kit-headless/src/components/select/select-inline.tsx
packages/kit-headless/src/components/select/select-root.tsx
packages/kit-styled/src/components/select/select.tsx

fixes the types for the Select component

fix(select): types for multiple yes/no

---

packages/kit-headless/src/components/modal/modal-panel.tsx

fix: modal animations

---

packages/kit-headless/src/components/toggle-group/toggle-group-root.tsx
packages/kit-headless/src/components/toggle-group/toggle-group.css

fix: tailwind on headless

---

.changeset/slow-socks-smell.md

add changelog

---

.github/workflows/test.yml

fix(test.yml): add run key to pagefind

---

.github/workflows/test.yml

fix(test.yml): add run key to pagefind #2

---

.github/workflows/test.yml

chore: temporarily remove needs: test for pkg-pr-new gh action

---

.github/workflows/test.yml

This reverts commit c788048b03040ff8d13e50a9439fa73187df146f.

Revert "chore: temporarily remove needs: test for pkg-pr-new gh action (#1040)"

---

.changeset/early-jokes-dress.md
README.md

Add sponsors section to the Readme

---

.changeset/giant-seals-whisper.md
packages/kit-headless/package.json
packages/kit-styled/package.json
packages/themes/package.json
packages/utils/package.json

add-license

---

.vscode/settings.json
apps/website/src/global.css
apps/website/src/routes/docs/headless/dropdown/index.mdx
apps/website/src/routes/docs/styled/dropdown/examples/hero.tsx
packages/kit-styled/src/components/breadcrumb/breadcrumb.tsx
packages/kit-styled/src/components/dropdown/dropdown.tsx

feat: styled dropdown

---

.changeset/tender-rocks-trade.md
apps/website/src/_state/component-statuses.ts
apps/website/src/routes/docs/headless/carousel/auto-api/api.ts
apps/website/src/routes/docs/styled/carousel/examples/hero-vertical.tsx
apps/website/src/routes/docs/styled/carousel/examples/hero.tsx
apps/website/src/routes/docs/styled/carousel/examples/pagination.tsx
apps/website/src/routes/docs/styled/carousel/examples/stepper.tsx
apps/website/src/routes/docs/styled/menu.md
apps/website/src/routes/layout.tsx
apps/website/vite.config.ts
packages/kit-styled/components-registry.json
packages/kit-styled/src/components/button/button.tsx
packages/kit-styled/src/components/carousel/carousel.tsx
packages/kit-styled/src/index.ts

feat(styled kit): carousel component

---

apps/website/src/routes/docs/styled/carousel/index.mdx
apps/website/src/routes/docs/styled/carousel/showcase-components.tsx

docs: fix carousel showcase

---

apps/website/src/_state/component-statuses.ts
apps/website/src/routes/docs/headless/tooltip/auto-api/api.ts
apps/website/src/routes/docs/headless/tooltip/index.mdx
apps/website/src/routes/docs/styled/menu.md
apps/website/src/routes/docs/styled/popover/index.mdx
apps/website/src/routes/docs/styled/tooltip/examples/hero.tsx
apps/website/src/routes/docs/styled/tooltip/showcase-components.tsx
packages/kit-headless/src/components/tooltip/tooltip-arrow.tsx
packages/kit-styled/src/components/tooltip/tooltip.tsx
packages/kit-styled/src/index.ts

feat(styled kit): tooltip component

---

.changeset/dirty-foxes-glow.md

chore: wrong changeset

---

.changeset/brave-pots-help.md
.changeset/tiny-beds-nail.md

chore: changesets

---

packages/kit-styled/package.json
pnpm-lock.yaml

fix: styled kit utils dep

---

package.json
pnpm-lock.yaml

fix: deployments not working with undici 7

---

package.json
pnpm-lock.yaml

fix: deployments not working with undici 7 (2)

---

packages/cli-e2e/src/cli.smoke.spec.ts

chore: re-enable cli smoke test
