qwikifiers/qwik-ui

- packages/daisy/src/components/tooltip/tooltip.tsx
- packages/daisy/src/index.ts
- packages/headless/src/components/tooltip/tooltip.css
- packages/headless/src/components/tooltip/tooltip.tsx
- packages/website/src/routes/daisy-example/index.tsx
Adds explicit states to the tool tip to handle 
- Hidden
- Positioned
- Unpositioned
- Closing
Adds default css transition with 100ms duration. Allows duration to be configured.
Adds Daisy implementation with basic styling.
There does not seem to be a way to map a named slot in Daisy to a named slot in Headless. Until a solution can be found tooltip content will have to be a simple string.
> Finish tooltip

- packages/daisy/src/components/button/button.tsx
- packages/headless/src/components/button/button.tsx
- packages/website/src/root.tsx
- packages/website/src/routes/docs/daisy/button/index.tsx
- packages/website/src/routes/docs/headless/button/index.tsx
`ButtonProps` are now typed to `QwikIntrinsicElements['button']` so the  `<Button />` component can be used with all HTMLButton properties
> fix(component): add TS support for HTMLButton properties

- packages/daisy/src/components/button/button.tsx
- packages/daisy/src/components/button/daisy.config.ts
- packages/website/src/routes/docs/daisy/button/index.tsx
- packages/website/src/routes/docs/headless/button/index.css
- [x ] Feature / enhancement
The Daisy Button variants  can be now handled by using a specific `variant` property. Example:
```
<Button variant="primary">
```
instead of:
```
<Button primary>
```
Furthermore I have also created a daisy.config file where I set all the CSS Daisy class names moving them from the component.
> refactor(component): refactoring Daisy Button props

- packages/daisy/src/components/card/card.tsx
- packages/headless/src/components/tabs/tabs.tsx
`className` property is now renamed in `classNames`
> style: rename className in classNames in Card and Tabs components

- CONTRIBUTING.md
- packages/website/src/routes/install/index.tsx
- packages/website/src/routes/install/layout.tsx
- packages/website/src/routes/use/index.tsx
- packages/website/src/routes/use/layout.tsx
I've updated the installation instructions on CONTRIBUTING.md to reflect the current directory structure and tools used in the project.
Storybook isn't currently used because of a technical limitation. 
Branch names are different than the ones specified in the docs.
- 1. I tried to install and got errors about missing package `core` (deprecated).
- 2. I expected to be able to install and run the project.
> docs: updating instalation instruction to reflect current setup

- packages/headless/src/components/rating/rating.tsx
I noticed the RatingIcon component did not have any key property (this was also logged in console)
```
2:54:54 PM [vite] page reload /Users/leonardo/PersProgetti/qwik-ui/packages/headless/src/components/rating/rating.tsx
QWIK ERROR JSXError: Multiple JSX sibling nodes with the same key.
This is likely caused by missing a custom key in a for loop
at eval (/src/rating_component_qsamuiuvsow.js:45:56)
at Array.map (<anonymous>)
at Rating_component_QSAMuIUvsOw (/src/rating_component_qsamuiuvsow.js:43:45)
at async Promise.all (index 0)
at async Promise.all (index 1)
at async Promise.all (index 1)
at async Promise.all (index 1)
at async Promise.all (index 1)
at async Promise.all (index 1)
at async Promise.all (index 0)
```
> fix(rating): add useId as key for each RatingIcon

- CODING_STANDARDS.md
Just found a space that was missing while reading the docs :)
> docs(coding standards): add missing space in header

- CONTRIBUTING.md
- apps/website/src/routes/docs/headless/rating/index.tsx
- package.json
- packages/daisy/src/components/rating/rating.tsx
- pnpm-lock.yaml
Fix website warnings/errors and update docs
> fix: docs and website

- apps/website/src/components/menu/menu.tsx
- apps/website/src/routes/docs/daisy/radio/index.tsx
- apps/website/src/routes/docs/headless/radio/index.tsx
- packages/daisy/src/components/ratio/daisy.config.ts
- packages/daisy/src/components/ratio/radio.tsx
- packages/daisy/src/index.ts
- packages/headless/src/components/radio/radio.tsx
- packages/headless/src/index.ts
> feat(component): add radio component

- packages/headless/src/components/select/select.tsx
Misko often points out that useClientEffect can be a footgun. When looking across many instances of components in a library, we can carve out some nice little performance boosts by just being aware of it. 
Did a slight rework to avoid it. Note he we can store signals for each option element in the contextService.options, rather than HTMLElements that we have to load in for the first time on client side. 
After making those changes, also noticed the setRef functions were a lil bit of extra overhead since we can set the ref directly. 
Original discussion popped up in Discord with Marcus: https://discord.com/channels/842438759945601056/1076533829373792296
> avoid use of useClientEffect in Headless Select

- apps/website/src/constants.ts
- apps/website/src/routes/layout.tsx
- packages/daisy/src/components/rating/rating.tsx
- packages/headless/src/components/drawer/drawer.tsx
- packages/headless/src/components/menu/menu.tsx
- packages/headless/src/components/popover/popover-content.tsx
- packages/headless/src/components/popover/popover-context.tsx
- packages/headless/src/components/popover/popover-trigger.tsx
- packages/headless/src/components/popover/popover.tsx
- packages/headless/src/components/select/select.tsx
- packages/headless/src/components/tabs/tabs.tsx
- packages/headless/src/components/tooltip/tooltip.tsx
Fix all occurrence for useClientEffect$ and createContext which are now considered deprecated hooks
> fix: deprecated useClientEffect$ and createContext hooks

- apps/website/src/global.css
Set the background color to the header based on the selected theme.
- 1. The header has no background yet
> fix(global.css): set background-color to header

- .gitignore
- apps/website/project.json
- package.json
- pnpm-lock.yaml
Bumped qwik-nx to the latest version and ran migration for the project.json. Apart from the migration also updated preview target to use @nrwl/vite:preview-server executor
> build: bump qwik-nx to v0.11

- package.json
- packages/daisy/vite.config.ts
- packages/headless/cypress.config.ts
- packages/headless/src/components/button/button.cy.tsx
- packages/headless/src/components/popover/popover.tsx
- packages/headless/vite.config.ts
- packages/material/vite.config.ts
- pnpm-lock.yaml
Cypress component testing wasn't working for libs. To fix this, should use `mode: 'lib'` when running cypress tests. Additionally, it is required to configure `server.fs.allow` in the `vite.config.ts`
> fix: update config to enable cypress component testing

- apps/website/src/routes/docs/daisy/pagination/index.tsx
- packages/daisy/src/components/pagination/pagination.tsx
- packages/headless/src/components/pagination/pagination.tsx
added props to pagination, siblingCount etc
206
Added optional props to pagination & copied functionality from [mui](https://mui.com/material-ui/react-pagination/#pagination-ranges)
`showFirstButton`
`showLastButton`
`hideNextButton`
`hidePrevButton`
`siblingCount`
`boundaryCount`
> feat(component): improve pagination

- apps/website/src/routes/docs/daisy/toggle/index.tsx
- packages/daisy/src/components/toggle/toggle.tsx
- packages/headless/src/components/toggle/toggle.tsx
I had a few issues implementing the toggle component on the pagination docs
Described at [#209](https://github.com/qwikifiers/qwik-ui/issues/209)
- HeadlessToggle expected a prop `pressed` and the DaisyToggle received `checked` and passed it as `pressed`, I renamed it.
- DaisyToggleProps interface didn't extend HeadlessToggleProps
- `pressed` and `defaultPressed` didn't were always initially `false`.
> fix(toggle component): renamed prop & change funcionality in Toggle

- apps/website/src/routes/docs/daisy/pagination/index.tsx
allow set options with the toggle component (and not the native checkbox)
Improved pagination docs by using the Toggle component instead of the native checkbox
Before
After
> docs(pagination docs): improved pagination docs

- apps/website/src/components/menu/menu.tsx
- apps/website/src/routes/docs/daisy/breadcrumb/BreadcrumbWrapper.tsx
- apps/website/src/routes/docs/daisy/breadcrumb/PathIcon.tsx
- apps/website/src/routes/docs/daisy/breadcrumb/index.tsx
- apps/website/src/routes/docs/headless/breadcrumb/BreadcrumbWrapper.css
- apps/website/src/routes/docs/headless/breadcrumb/BreadcrumbWrapper.tsx
- apps/website/src/routes/docs/headless/breadcrumb/PathIcon.tsx
- apps/website/src/routes/docs/headless/breadcrumb/index.css
- apps/website/src/routes/docs/headless/breadcrumb/index.tsx
- packages/daisy/src/components/breadcrumb/breadcrumb-item.tsx
- packages/daisy/src/components/breadcrumb/breadcrumb.tsx
- packages/daisy/src/components/breadcrumb/index.ts
- packages/daisy/src/index.ts
- packages/headless/src/components/breadcrumb/breadcrumb-item.css
- packages/headless/src/components/breadcrumb/breadcrumb-item.tsx
- packages/headless/src/components/breadcrumb/breadcrumb.css
- packages/headless/src/components/breadcrumb/breadcrumb.tsx
- packages/headless/src/components/breadcrumb/index.ts
- packages/headless/src/index.ts
Add Breadcrumb component (headless and daisy) and Breadcrumb component  website docs
Add a new Breadcrumb component (headless & daisy)
> feat(component): add new Breadcrumb component

- CODING_STANDARDS.md
At the current state, there isn't consistency between how components are exposing their props.
Some are using interfaces while others are using types.
Also, when extending from headless, there are different behaviors in how the headless props are extended/redefined and how variant types (e.g. `DaisyTooltipProps`) are defined.
Besides, there's no clear naming convention on exported types/interfaces.
This PR aims to define a clear guideline so that we can refactor the existing components and be more consistent from now on.
The current version is just a proposal, feedback of all kind are welcome!
---
Some extra thoughts I had while writing:
- Why types over interfaces? I think they're easier to handle with intersection types (`&`) rather than with interface extensions.
- How should we define …
> docs(coding standards): define a coding standard for exposing components' props

- CODING_STANDARDS.md
- packages/headless/src/components/action-button/action-button.tsx
- packages/primitives/src/lib/alert/alert.tsx
- packages/primitives/src/lib/button/button.tsx
- packages/primitives/src/lib/progress/progress.tsx
- packages/primitives/src/lib/radio/radio.tsx
- packages/primitives/src/lib/toast/toast.tsx
- packages/primitives/src/lib/toggle/toggle.tsx
Change the primitives components to be lite components.
> refactor(components): change primitives to lite components

- packages/kit-headless/package.json
- packages/kit-material/package.json
- packages/kit-tailwind/package.json
For some reason, the generated types path was added the "qwik-ui" folder (which wasn't there before)
> fix: types path in all packages

- apps/website/src/_state/component-statuses.ts
- apps/website/src/routes/docs/_components/anatomy-table/anatomy-table.tsx
- apps/website/src/routes/docs/headless/(components)/accordion/examples.tsx
- apps/website/src/routes/docs/headless/(components)/accordion/index.mdx
- packages/kit-headless/src/components/accordion/accordion-content.tsx
- packages/kit-headless/src/components/accordion/accordion-context.type.ts
- packages/kit-headless/src/components/accordion/accordion-header.tsx
- packages/kit-headless/src/components/accordion/accordion-item.tsx
- packages/kit-headless/src/components/accordion/accordion-root.tsx
- packages/kit-headless/src/components/accordion/accordion-trigger.tsx
- packages/kit-headless/src/components/accordion/accordion.spec.tsx
- packages/kit-headless/src/components/autocomplete/autocomplete-input.tsx
> Accordion: Ready State

- apps/website/package.json
Instead of linking to `dist`, I found out we can link to `workspace:*` and it should still work fine and build the website without errors
> build(website): changed to pnpm workspace links

- apps/website/src/root.tsx
Add window.matchMedia as a fallback to determine light/dark theme when there's no localStorage value for theme-settings
- [+] Bug
Tiny change to fix the website header.
Described here https://github.com/qwikifiers/qwik-ui/issues/392
- [+] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-ui/blob/main/CONTRIBUTING.md)
- [+] I have performed a self-review of my own code
- [n/a] I have made corresponding changes to the documentation
- [n/a] Added new tests to cover the fix / functionality
> fix(website): fix initial theme usage when os is in dark mode

- apps/website/src/_state/component-statuses.ts
- apps/website/src/routes/docs/_components/status-banner/status-banner.tsx
- apps/website/src/routes/docs/headless/(components)/separator/examples.tsx
- apps/website/src/routes/docs/headless/(components)/separator/index.mdx
- apps/website/src/routes/docs/headless/menu.md
- packages/kit-headless/src/components/separator/separator.spec.tsx
- packages/kit-headless/src/components/separator/separator.tsx
- packages/kit-headless/src/index.ts
Addition of a headless separator component closes #397. This is my first time contributing to open-source so I decided to start off with a simple yet handy component in the separator. 
The separator component complies to the WAI-Aria separator role. It is currently only static. In the future the separator could updated to be made focusable and used for interactivity. However, I think creating headless window splitter component that follows the [WAI Splitter Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/windowsplitter/) would make more sense.
The implementation follows very closely to how it is implemented in radix ui for react.  [Radix separator](https://www.radix-ui.com/primitives/docs/components/separator) for reference,
1. Creating a division between items in a menu
- Visually …
> feat(headless): separator component

- packages/kit-headless/package.json
- packages/kit-headless/vite.config.ts
- packages/kit-tailwind/package.json
- pnpm-lock.yaml
- since packages were depending on a lower version they still exhibited the TS4023 error
- using the latest qwik version resolves that
fix #396
To successfully generate the missing d.ts files (as per the bug #396)
> fix(bump qwik dep version): bump qwik peer dep in packages

- CONTRIBUTING.md
- package.json
> refactor(package.json & contributing.md): add pnpm link.dist script

- packages/kit-headless/vite.config.ts
fix #473
vite.config.ts had `external: ['@floating-ui/dom', 'country-list-json', 'libphonenumber-js']`.
I think the problem is that if headless kit uses any of these packages for UI behavior, each package has to be added to the @qwik-ui/headless bundle. Otherwise Rollup has no way to resolve the package.
Hence I propose removing all of that `external: ['@floating-ui/dom', 'country-list-json', 'libphonenumber-js']` line for now. I tested this using pnpm link and it seemed to solve #473. Can we try to merge this and see if it works? We can always revert if it doesn't, and try to optimize the final bundles later if it does.
> fix(vite.config.ts): remove external rollupOptions

- packages/kit-headless/src/components/accordion/accordion-trigger.tsx
In Safari you can click on the +/- icon for accordion and the contents are still shown. this fixes that by avoiding the onclick handlers
> fix(accordion): disabled in safari

- apps/website/src/routes/docs/_components/anatomy-table/anatomy-table.tsx
Add support for custom column label
Example:
```tsx
<AnatomyTable
firstColumnLabel="Property"
propDescriptors={[
{
name: 'disable',
description: '...',
},
]}
/>
```
> feat(anatomy-table): add support for custom column label

- apps/website/src/routes/docs/headless/(components)/pagination/examples/basic.tsx
- apps/website/src/routes/docs/headless/(components)/pagination/examples/custom-arrows.tsx
- apps/website/src/routes/docs/headless/(components)/pagination/examples/custom-button-labels.tsx
- apps/website/src/routes/docs/headless/(components)/pagination/examples/disabled.tsx
- apps/website/src/routes/docs/headless/(components)/pagination/examples/hide-prev-next-buttons.tsx
- apps/website/src/routes/docs/headless/(components)/pagination/examples/interactive.tsx
- apps/website/src/routes/docs/headless/(components)/pagination/examples/styling.tsx
- apps/website/src/routes/docs/headless/(components)/pagination/index.css
- apps/website/src/routes/docs/headless/(components)/pagination/index.mdx
- packages/kit-headless/src/components/pagination/pagination.spec.tsx
- packages/kit-headless/src/components/pagination/pagination.tsx
- packages/kit-headless/src/components/pagination/types/pagination-api.ts
- packages/kit-headless/src/components/pagination/use-pagination.spec.ts
- packages/kit-headless/src/components/pagination/use-pagination.ts
1. BEHAVIORS
I have fixed how items are generated the pagination item.
The new algorithm does not support `boundaryCount` anymore but it should mimic the [melt-ui pagination component](https://www.melt-ui.com/docs/builders/pagination).  
A preview:
https://github.com/qwikifiers/qwik-ui/assets/1772083/98e871c0-75cc-47ee-84a0-df2db40a0dd6
2. DOCUMENTATION
I have added styles to the documentation. 
This doc is still not completed but it should be more consistent and prettier than previous version
3. FIXED
I have fixed some behaviors:
- NEXT and PREV buttons are not hidden anymore but just disabled
- Added new properties to customize the look & feel of NEXT / PREV  buttons
- Some minor fixes
> fix: pagination

- README.md
Hello, first PR here 👋
I noticed that the all-contributors badge at the top of the README is static (and quite behind the actual count).
Fortunately badges.io right now provides an [endpoint](https://shields.io/badges/git-hub-contributors-from-allcontributors-org) just for this 😃
I've changed the endpoint but kept the same style.
> docs(readme): dynamic all-contributors badge

- package.json
- pnpm-lock.yaml
preview and preview.cloudflare don't work anymore:
> Argument of type 'import("/home/maieul/dev/qwik-ui/node_modules/.pnpm/vite@4.4.9_@types+node@20.5.7_sass@1.66.1/node_modules/vite/dist/node/index").UserConfigExport' is not assignable to parameter of type 'import("/home/maieul/dev/qwik-ui/node_modules/.pnpm/vite@4.5.0_@types+node@20.5.7_sass@1.66.1/node_modules/vite/dist/node/index").UserConfigExport'.
So I updated vite to 4.5.0 and it solves the issue.
> docs: fix website preview and preview.cloudflare bug because of vite version

- .eslintrc.json
- apps/website/src/components/highlight/highlight.tsx
- apps/website/src/components/mdx-components/index.tsx
- apps/website/src/components/navigation-docs/navigation-docs.tsx
- apps/website/src/components/note/note.tsx
- apps/website/src/routes/docs/fluffy/(getting-started)/introduction/index.mdx
- apps/website/src/routes/docs/fluffy/pagination/_index.tsx
- apps/website/src/routes/docs/headless/checkbox/index.tsx
- apps/website/src/routes/docs/headless/pagination/examples/interactive.tsx
- apps/website/src/routes/docs/headless/radio/index.tsx
- packages/kit-fluffy/src/components/button/button.tsx
- packages/kit-fluffy/vite.config.ts
- packages/kit-tailwind/src/components/breadcrumb/breadcrumb-item.tsx
- packages/kit-tailwind/src/components/breadcrumb/breadcrumb.tsx
- packages/kit-tailwind/src/components/button-group/button-group.tsx
- packages/kit-tailwind/src/components/card/card-actions.tsx
- packages/kit-tailwind/src/components/card/card-image.tsx
- packages/kit-tailwind/src/components/card/card-title.tsx
- packages/kit-tailwind/src/components/card/card.tsx
- packages/kit-tailwind/src/components/navigation-bar/navigation-bar.tsx
- packages/kit-tailwind/src/components/progress/progress.tsx
- packages/kit-tailwind/src/components/ratio/radio.tsx
- packages/kit-tailwind/src/components/slider/slider.tsx
- packages/kit-tailwind/src/components/tabs/tab.tsx
- packages/kit-tailwind/src/components/toast/toast.tsx
- packages/kit-tailwind/vite.config.ts
- packages/primitives/vite.config.ts
- packages/utils/vite.config.ts
Docs improvements:
- background on mobile nav
- no bottom margin on single paragraph notes
This PR intends to allow us to run the preview, because we currently can't.
- Disable the visible task eslint error preventing build
- ts-ignore the deprecated kit tailwind after the new type changes
- remove unnecessary test properties in vite config
What's left:
- the ?jsx syntax completely broke. Likely because vite-imagetools depends on a cjs api and vite 5 just deprecated it.
- there is also currently an issue with the build and images on preview. They work on dev, but do not work on preview.
> fix(everything): fix 1.3 craziness

- apps/website/src/routes/docs/headless/modal/examples/animation.tsx
- apps/website/src/routes/docs/headless/modal/examples/auto-focus.tsx
- apps/website/src/routes/docs/headless/modal/examples/backdrop-close.tsx
- apps/website/src/routes/docs/headless/modal/examples/backdrop.tsx
- apps/website/src/routes/docs/headless/modal/examples/bottom-sheet.tsx
- apps/website/src/routes/docs/headless/modal/examples/inspect.tsx
- apps/website/src/routes/docs/headless/modal/examples/main.tsx
- apps/website/src/routes/docs/headless/modal/examples/sheet.tsx
- apps/website/src/routes/docs/headless/modal/examples/transition.tsx
Better semantic HTML.
This commit makes the code closer to the W3C's recommendation, which are quoted below, in two important ways:
- 1. Removes `fieldsets` that had no legends
> The first element inside the fieldset must be a legend element, which provides a label or description for the group
[source](https://www.w3.org/WAI/WCAG21/Techniques/html/H71)
- 2. Applies the recommended pattern for *self-explanatory* forms like the ones used in the examples by replacing the `fieldsets` with `divs`, relying solely on the labels for meaning
> when [...] the individual label associated with each particular control provides a sufficient description [...] the use of the fieldset and legend elements is not required
[source](https://www.w3.org/WAI/WCAG21/Techniques/html/H71)
Alternately, we could add …
> refactor(modal/examples): replaces fieldsets in example code

- apps/website/src/components/mdx-components/index.tsx
Added twMerge to components in case we'd like to override the classes in the .mdx files with the HTML tags.
> docs(mdx-components): add twMerge to components

- apps/website/src/components/navigation-docs/navigation-docs.tsx
This change improves the "click" behaviror. Because of current wrapping sequence, you must click on the text instead of the container to trigger url. Now clicking on the container, or text, will trigger url.
More uniform behavior across navigation component.
https://github.com/qwikifiers/qwik-ui/assets/102767512/2943b952-29f1-41ca-bda4-b6047285c105
> refactor(navigation-docs): make <a> wrap <li> instead of <li> wrap <a>

- apps/website/src/components/header/header.tsx
Fixes flashing light-theme icon when changing pages in dark mode. 
- 1. More refined user experience
https://github.com/qwikifiers/qwik-ui/assets/102767512/8bec014c-3cff-446f-b6d5-62eac62fb417
> fix(header.tsx): flashing theme icon when switching pages in dark mode

- packages/kit-fluffy/src/components/input/input.tsx
> revert(fluffy input): re-add component with fixed types and cn helper

- packages/kit-headless/vite.config.ts
For two reasons:
- the namespace issues (see https://github.com/qwikifiers/qwik-ui/pull/521 which also links to https://github.com/qwikifiers/qwik-ui/issues/519 for a more thorough explanation)
- the SSG build hang issue (see https://github.com/qwikifiers/qwik-ui/issues/577 wich is likely the same bug as https://github.com/qwikifiers/qwik-ui/issues/519)
Until https://github.com/BuilderIO/qwik/issues/5473 gets solved in Qwik, I say we temporarily disable preserveModules. We will have less performance (it should be about 11kb more instead of 40 now that the repo is cleaned up) in favor of more stability.
> fix(preservemodules): temporarily remove preserveModules

- packages/kit-headless/src/components/modal/modal.tsx
when you press Enter then ESC the dialog will be out of sync with the signal
> fix(dialog): ESC freezes browser

- .changeset/lazy-eels-peel.md
- apps/website/src/routes/docs/headless/combobox/examples/context.tsx
- apps/website/src/routes/docs/headless/combobox/examples/custom-filter.tsx
- apps/website/src/routes/docs/headless/combobox/examples/custom-keys.tsx
- apps/website/src/routes/docs/headless/combobox/examples/default-label.tsx
- apps/website/src/routes/docs/headless/combobox/examples/disable-blur.tsx
- apps/website/src/routes/docs/headless/combobox/examples/disabled.tsx
- apps/website/src/routes/docs/headless/combobox/examples/hero.tsx
- apps/website/src/routes/docs/headless/combobox/examples/hide.tsx
- apps/website/src/routes/docs/headless/combobox/examples/highlighted-index.tsx
- apps/website/src/routes/docs/headless/combobox/examples/object.tsx
- apps/website/src/routes/docs/headless/combobox/examples/placement.tsx
- apps/website/src/routes/docs/headless/combobox/examples/search-bar.tsx
- apps/website/src/routes/docs/headless/combobox/examples/signal-binds.tsx
- apps/website/src/routes/docs/headless/combobox/examples/sort-filter.tsx
- apps/website/src/routes/docs/headless/combobox/examples/string.tsx
- packages/kit-headless/src/components/combobox/combobox.driver.ts
- packages/kit-headless/src/components/combobox/combobox.test.ts
Fixes #661 
Here is the updated UX with dark mode configured
Light mode is fixed as well
> fix(headless/combobox): fix dark mode and add basic a11y tests

- apps/website/src/routes/docs/headless/select/examples/form.tsx
- apps/website/src/routes/docs/headless/select/index.mdx
- packages/kit-headless/src/components/select/hidden-select.tsx
- packages/kit-headless/src/components/select/select-option.tsx
- packages/kit-headless/src/components/select/select.driver.ts
- packages/kit-headless/src/components/select/select.test.ts
- packages/kit-headless/src/components/select/select.tsx
This PR adds the initial form control logic with a native select to our headless select implementation. This way we can leverage the browser form controls.
(we also remove the test id's in the MDX, as they are no longer needed with the new `component-tests` app in the monorepo)
> feat(select): initial form logic

- apps/website/src/components/copy-css-config/copy-css-config.tsx
- the height  of `Copy Code` section was more than 100vh. 
before:
after:
> docs: fix height of `copy-css`

- .changeset/tough-keys-rest.md
- apps/website/src/routes/docs/headless/popover/examples/anchor-ref.tsx
- apps/website/src/routes/docs/headless/popover/index.mdx
- apps/website/src/routes/docs/headless/popover/snippets/floating.css
- packages/kit-headless/src/components/popover/popover.css
- packages/kit-headless/src/components/popover/popover.tsx
Data attribute that styles floating behavior
It was much more effort on the consumer to use. This gives a much more sensible default.
> Deprecate listbox class in favor of floating mode default

- apps/website/src/routes/docs/styled/skeleton/index.mdx
Skeleton currently has the text from separator.
> doc: fix skeleton text

- .changeset/breezy-crabs-film.md
- apps/website/src/routes/docs/headless/select/examples/bind-open.tsx
- apps/website/src/routes/docs/headless/select/index.mdx
- packages/kit-headless/src/components/select/select.test.ts
- packages/kit-headless/src/components/select/select.tsx
This PR allows consumers to programmatically control when the select opens or closes. This can be useful for a multi-step form, or other custom behaviors.
> feat: bind:open prop on select

- apps/website/src/routes/docs/headless/modal/index.mdx
Modal event hook is onClose not onHide anymore
> docs: modal: change onHide to onClose

- apps/website/src/routes/docs/headless/select/examples/controlled-value.tsx
- use id-s to remove the confusion of select being a value or an id of a value
> chore: update select controlled example

- packages/kit-headless/src/components/modal/use-modal.tsx
`transitionend` and `animationend` events were apparently being triggered on dialog children as well.
Here's a recording where you can see me closing the modal normally by pressing escape once and clicking on the backdrop twice. But then I hover over the border-radius 0 button which has a `transition-all duration-100`class that triggers the event callback (in this case just by hovering on the button, but it could happen on click as well). 
https://github.com/qwikifiers/qwik-ui/assets/45822175/8cb5cc2b-1e80-45ab-802d-5676b11c2cf6
Here's the expanded animationend event object when clicking on the backdrop:
Here's the expanded transitionend event object when hovering on the button:
As you can see the target the first time is the dialog element, whereas the second time it's the button 😱
So …
> fix(headless modal): prevent bubbling of animationend and transitionend event listeners

- .changeset/fast-actors-report.md
- apps/website/src/routes/docs/styled/input/examples/hero.tsx
- packages/kit-styled/src/components/input/input.tsx
Workaround/Fix for #764
Workaround so the styled input is functional until `bind:value` prop can be conditional in Qwik core.
> fix: input and bind:value

- .changeset/olive-sheep-run.md
- apps/website/src/routes/docs/headless/select/snippets/select.css
- packages/kit-headless/src/components/select/select-context.ts
- packages/kit-headless/src/components/select/select-item.tsx
- packages/kit-headless/src/components/select/select-root.tsx
- packages/kit-headless/src/components/select/select-trigger.tsx
- packages/kit-headless/src/components/select/select.driver.ts
- packages/kit-headless/src/components/select/select.test.ts
> Select focus navigation refactor

- .changeset/purple-games-ring.md
- apps/website/src/routes/docs/headless/select/snippets/select.css
- packages/kit-headless/src/components/select/hidden-select.tsx
- packages/kit-headless/src/components/select/select-context.ts
- packages/kit-headless/src/components/select/select-description.tsx
- packages/kit-headless/src/components/select/select-label.tsx
- packages/kit-headless/src/components/select/select-root.tsx
- packages/kit-headless/src/components/select/select-trigger.tsx
> fix: disabled select

- .changeset/rich-windows-admire.md
- packages/kit-headless/src/components/modal/use-modal.tsx
- [ X] Bug
There was an issue where clicking onto the pane of the modal and pressing escape would cause future attempts at opening the modal to bug out.
[Bug Link](https://github.com/qwikifiers/qwik-ui/issues/817)
[After Fix](https://jam.dev/c/f098c32a-3a9c-4657-ad44-4737086898f0)
> fix: Only run single modal close step

- .changeset/little-llamas-brake.md
- packages/kit-headless/src/components/select/select-item-indicator.tsx
In order to style the select item indicator, we need to pass the class property.
> fix: pass down select item indicator props

- apps/website/src/routes/index@landing.tsx
Today, the headless kit's image alt is `styled kit`, this PR corrects it to `headless kit`.
> fix(landing): correct image alt

- apps/website/src/routes/docs/styled/breadcrumb/index.mdx
- packages/kit-styled/src/components/breadcrumb/breadcrumb.tsx
Because we spread props after the class attribute, It gets overridden instead of concatenated with the `cn` function.
I have checked other components and it seems this problem is only in the Breadcrumb component.
> fix: breadcrumb class override instead of concatenate

- apps/website/src/routes/docs/headless/popover/examples/toggle-event.tsx
- apps/website/src/routes/docs/headless/popover/index.mdx
Documented existing `onChange$` functionality on the `<Popover.Panel>` component that allows a user to track the current state of the popover.
> Updated popover docs to show onToggle

- apps/website/src/components/highlight/highlight.tsx
Preview route transitions are now much faster, shiki should now be working correctly in dev mode and preview, as I believe the previous error was due to multiple instances being created each time an example was rendered.
> single shiki instance & on the server w/ dev

- apps/component-tests/src/components/showcase-test/component-imports.ts
- apps/website/src/components/code-snippet/code-snippet.tsx
- apps/website/src/components/showcase/component-imports.ts
- apps/website/src/components/showcase/showcase.tsx
- apps/website/vite.config.ts
> Remove-import-meta-glob-eager-true

- .github/workflows/test.yml
I don't remember why we sticked to 0.0.9. Latest version seems to be 0.0.20.
> chore(pkg.pr.new): remove 0.0.9 flag

- apps/website/vite.config.ts
Eslint working in VSCode should be enough.
> chore(website): disable qwikVite linter to speed up preview and builds

- apps/website/auto-api.ts
•	Variable Renaming: Changed variable names like lol to capture and hacky to exportedApi for better readability.
•	Regex Enhancements: Updated regex patterns to be platform-independent by matching both / and \ using [\\/].
•	Edge Case Handling: Added checks to prevent accessing undefined variables when arrays may be empty.
•	Error Logging: Included error logging in the catch block of writeToDocs to output any errors during file writing.
•	Path Handling: Used path.resolve to handle file paths in a platform-independent way.
•	Comment Trimming: Trimmed comments to remove unnecessary whitespace.
> refactor(auto-api.ts): chatgpt o1 cleanup

- apps/website/auto-api.ts
TLDR: current query only works if you are exporting the type because its too strict, so this fixes that.
> fix(auto api): query too strict

- .changeset/soft-snakes-sniff.md
- .github/workflows/test.yml
- package.json
- packages/cli-e2e/src/cli.smoke.spec.ts
- packages/cli/bin/index.ts
the cli asks for a root folder and `global.css` location, but it doesn't check the css location relative to the root. 
This fixes it
> fixed cli not checking relative global.css correctly

- apps/component-tests/src/root.tsx
- apps/website/src/components/module-preload/module-preload.tsx
- apps/website/src/root.tsx
- package.json
- pnpm-lock.yaml
> Add module preloading at idle time

- .changeset/fluffy-turkeys-grow.md
- packages/cli/src/generators/component/component-generator.spec.ts
- packages/cli/src/generators/component/component-generator.ts
This makes the styled-kit much easier to import components from. 
Every generated file is added to the barrel file (`index.ts`) on the root of the component folder. 
That way you can just import all generated styled components from a single point instead of `;/input/input` etc.
> added barrel file generation

- .github/ISSUE_TEMPLATE/bug.yaml
- apps/website/public/_redirects
Now qwik-ui users can create a fast reproduction for bugs using our new stackblitz starter.
**Link to reproduction stackblitz:**
https://qwikui.com/repro
**Github repository:**
https://github.com/qwikifiers/qwik-ui-stackblitz
All qwik-ui maintainers have write permission to this repo so it could be maintained when we add new components .
> added redirect to repro stackblitz

- apps/website/auto-api.ts
- apps/website/src/components/api-table/auto-api.tsx
This PR adds missing functionality that prevents the auto api from being used in all headless components.
No major changes were needed, so should be an easy review.
> Auto api better query

- .changeset/shy-bottles-agree.md
- .changeset/tender-pens-run.md
- apps/website/src/routes/docs/styled/accordion/examples/hero.tsx
- apps/website/src/routes/docs/styled/accordion/index.mdx
- packages/kit-headless/src/components/modal/modal-trigger.tsx
- packages/kit-headless/src/components/select/select-inline.tsx
- packages/kit-headless/src/components/select/select-root.tsx
- packages/kit-styled/src/components/select/select.tsx
This is also reverts https://github.com/qwikifiers/qwik-ui/commit/7a98c2c695a1c2f5e0f09a5e544370b3f4504ae1
> Styled accordion 100 score on lighthouse

- .changeset/wild-tools-brush.md
- apps/website/src/routes/docs/headless/carousel/auto-api/api.ts
- apps/website/src/routes/docs/headless/carousel/examples/carousel.css
- apps/website/src/routes/docs/headless/carousel/examples/mousewheel.tsx
- apps/website/src/routes/docs/headless/carousel/index.mdx
- packages/kit-headless/src/components/carousel/context.ts
- packages/kit-headless/src/components/carousel/root.tsx
- packages/kit-headless/src/components/carousel/scroller.tsx
> Carousel mousewheel

- apps/website/src/routes/docs/headless/carousel/examples/hero.tsx
- packages/kit-headless/src/components/carousel/carousel.css
- packages/kit-headless/src/components/carousel/carousel.test.ts
- packages/kit-headless/src/components/carousel/scroller.tsx
- packages/kit-headless/src/components/carousel/slide.tsx
> carousel fixes

- .changeset/old-ladybugs-pump.md
- .github/workflows/test.yml
- apps/website/src/routes/docs/headless/combobox/examples/scrollable.tsx
- apps/website/src/routes/docs/headless/select/auto-api/api.ts
- apps/website/src/routes/docs/headless/select/examples/first-value-selected.tsx
- apps/website/src/routes/docs/headless/select/examples/scrollable.tsx
- packages/kit-headless/src/components/combobox/combobox-item.tsx
- packages/kit-headless/src/components/select/select-context.ts
- packages/kit-headless/src/components/select/select-item.tsx
- packages/kit-headless/src/components/select/select-popover.tsx
- packages/kit-headless/src/components/select/select-root.tsx
- packages/kit-headless/src/components/select/select-trigger.tsx
- packages/kit-headless/src/components/select/select.test.ts
Fixes #1001 and #979, also infinite scrolling behavior
> Select fixes 0.6.5

- packages/kit-headless/src/components/accordion/accordion-inline.tsx
- packages/kit-headless/src/components/carousel/inline.tsx
- packages/kit-headless/src/components/toggle-group/toggle-group-item.tsx
- packages/kit-styled/src/components/toggle-group/toggle-group.tsx
cc @thejackshelton we need to avoid importing from e.g. @qwik-ui/headless inside the headless package itself, otherwise the optimizer adds unrelated imports to a component when building the lib, which leads to over-prefetching to consumers of that lib.
Here the toggle-group-item imports a lot of components from Accordion and Dropdown (because it's an MRE and there's only Accordion, Dropdown, Toggle and ToggleGroup). This will lead to over-prefetching.
> fix: recursive alias imports

- .changeset/popular-cups-study.md
- packages/kit-headless/src/components/select/select-inline.tsx
- packages/kit-headless/src/components/select/select-item.tsx
> select fixes

- apps/website/src/routes/docs/styled/(getting-started)/install/index.mdx
To show some love to users of JetBrains IDEs ♥️
> docs(styled/install): add steps for Tailwind CSS configuration for JetBrains IDEs

- .changeset/fair-women-cover.md
- apps/website/src/components/highlight/highlight.tsx
- apps/website/src/components/showcase/showcase.tsx
- apps/website/src/routes/docs/headless/collapsible/auto-api/api.ts
- apps/website/src/routes/docs/styled/carousel/examples/hero-vertical.tsx
- apps/website/src/routes/docs/styled/carousel/examples/hero.tsx
- apps/website/src/routes/docs/styled/carousel/examples/pagination.tsx
- apps/website/src/routes/docs/styled/collapsible/examples/hero.tsx
- apps/website/src/routes/docs/styled/collapsible/index.mdx
- apps/website/src/routes/docs/styled/collapsible/showcase-components.tsx
- apps/website/src/routes/docs/styled/menu.md
- packages/kit-styled/components-registry.json
- packages/kit-styled/src/components/accordion/accordion-todo.md
- packages/kit-styled/src/components/carousel/carousel.tsx
- packages/kit-styled/src/components/collapsible/collapsible.tsx
- packages/kit-styled/src/index.ts
> feat(styled kit): collapsible component

- .changeset/shiny-emus-visit.md
- apps/website/src/routes/docs/styled/modal/index.mdx
- packages/kit-styled/src/components/modal/modal.tsx
This PR fixes alignment issues with Modals when position is set to bottom or right
- [*] Bug
When trying to use Modal a Sheet it does not align properly when position set is either bottom or right
- [*] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-ui/blob/main/CONTRIBUTING.md)
- [*] I have performed a self-review of my own code
- [*] I have ran `pnpm change` and documented my changes
> fix: styled modal alignment

- .changeset/sour-walls-lay.md
- apps/website/src/routes/docs/styled/checkbox/index.mdx
- apps/website/src/routes/docs/styled/input/index.mdx
- apps/website/src/routes/docs/styled/textarea/index.mdx
- packages/kit-styled/src/components/checkbox/checkbox.tsx
- packages/kit-styled/src/components/input/input.tsx
- packages/kit-styled/src/components/textarea/textarea.tsx
> fix(styled kit): allow consumer to pass onInput$ with two way data-binding & fix forms
